### ISSUE TITLE
Automatically re-try failed HTTP requests

### ISSUE THREAD

**Issue by deckerego** [deckerego/SprinklerSwitch#19]
HTTP requests to the NOAA API time out fairly regularly around midnight. We should add an automatic retry; it doesn't need a backoff, just a few retries after waiting 120 seconds.

**Comment by deckerego** [comment]
Stack trace on network failure:
```
node:internal/deps/undici/undici:12345
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at node:internal/deps/undici/undici:12345:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/deckerego/Projects/SprinklerSwitch/node_modules/noaa-gfs-js/index.js:132:26
    at async GfsPort.getMetric (/Users/deckerego/Projects/SprinklerSwitch/src/ports/gfs.js:5:16)
    at async GfsRepository.getMetric (/Users/deckerego/Projects/SprinklerSwitch/src/repositories/gfs.js:99:24)
    at async GfsRepository.getAggregateMetric (/Users/deckerego/Projects/SprinklerSwitch/src/repositories/gfs.js:78:25)
    at async GfsRepository.getPrecipitationRate (/Users/deckerego/Projects/SprinklerSwitch/src/repositories/gfs.js:21:16)
    at async Promise.all (index 0)
    at async MetricsService.fetch (/Users/deckerego/Projects/SprinklerSwitch/src/services/metrics.js:11:22)
    at async /Users/deckerego/Projects/SprinklerSwitch/src/sprinkler.js:8:17 {
  cause: Error: getaddrinfo ENOTFOUND nomads.ncep.noaa.gov
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'nomads.ncep.noaa.gov'
  }
}
```

**Comment by deckerego** [comment]
Resolved by #30

**Comment by deckerego** [comment]
Yet another failure:
```
/opt/sprinklerswitch/repositories/gfs.js:61
                uValue: resultU.value,
                                ^

TypeError: Cannot read properties of undefined (reading 'value')
    at /opt/sprinklerswitch/repositories/gfs.js:61:33
    at Array.map (<anonymous>)
    at GfsRepository.getWindSpeed (/opt/sprinklerswitch/repositories/gfs.js:5>
    at process.processTicksAndRejections (node:internal/process/task_queues:9>
    at async Promise.all (index 5)
    at async MetricsService.fetch (/opt/sprinklerswitch/services/metrics.js:1>
    at async /opt/sprinklerswitch/sprinkler.js:8:17
```

**Comment by deckerego** [comment]
The `TypeError: Cannot read properties of undefined (reading 'value')` issue still occurs without retry
